export type { Font, FontMetrics } from './metrics.js';
export { WIN_ANSI_ENCODING, MAC_ROMAN_ENCODING, encodeWinAnsi, encodeMacRoman, isWinAnsiEncodable } from './encoding.js';
export { StandardFonts, getStandardFont, STANDARD_FONT_NAMES } from './standard-fonts.js';
export type { StandardFontName } from './standard-fonts.js';
export { parseTrueTypeFont } from './truetype-parser.js';
export type { TrueTypeFontData, HeadTable, HheaTable, HmtxTable, NameTable, Os2Table, PostTable, MaxpTable } from './truetype-parser.js';
export { subsetTrueTypeFont } from './font-subsetter.js';
export type { SubsetResult } from './font-subsetter.js';
export { embedStandardFont, embedTrueTypeFont } from './font-embedder.js';
export { generateToUnicodeCMap } from './glyph-mapping.js';
export { FontManager } from './font-manager.js';
export type { EmbeddedFont } from './font-manager.js';
