export const StructureTags = {
  Document: 'Document',
  Part: 'Part',
  Art: 'Art',
  Sect: 'Sect',
  Div: 'Div',
  BlockQuote: 'BlockQuote',
  Caption: 'Caption',
  TOC: 'TOC',
  TOCI: 'TOCI',
  Index: 'Index',
  NonStruct: 'NonStruct',
  Private: 'Private',
  H: 'H',
  H1: 'H1',
  H2: 'H2',
  H3: 'H3',
  H4: 'H4',
  H5: 'H5',
  H6: 'H6',
  P: 'P',
  L: 'L',
  LI: 'LI',
  Lbl: 'Lbl',
  LBody: 'LBody',
  Table: 'Table',
  TR: 'TR',
  TH: 'TH',
  TD: 'TD',
  THead: 'THead',
  TBody: 'TBody',
  TFoot: 'TFoot',
  Span: 'Span',
  Quote: 'Quote',
  Note: 'Note',
  Reference: 'Reference',
  BibEntry: 'BibEntry',
  Code: 'Code',
  Link: 'Link',
  Annot: 'Annot',
  Ruby: 'Ruby',
  Warichu: 'Warichu',
  Figure: 'Figure',
  Formula: 'Formula',
  Form: 'Form',
} as const;

export type StructureTag = typeof StructureTags[keyof typeof StructureTags];
